// Code generated by MockGen. DO NOT EDIT.
// Source: ./payment.go
//
// Generated by this command:
//
//	mockgen -source=./payment.go -destination=../../mock/payment_port.go -package=mock -mock_names=Repository=MockPaymentClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/jorgeAM/grpc-kata-order-service/internal/order/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentPort is a mock of PaymentPort interface.
type MockPaymentPort struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentPortMockRecorder
	isgomock struct{}
}

// MockPaymentPortMockRecorder is the mock recorder for MockPaymentPort.
type MockPaymentPortMockRecorder struct {
	mock *MockPaymentPort
}

// NewMockPaymentPort creates a new mock instance.
func NewMockPaymentPort(ctrl *gomock.Controller) *MockPaymentPort {
	mock := &MockPaymentPort{ctrl: ctrl}
	mock.recorder = &MockPaymentPortMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentPort) EXPECT() *MockPaymentPortMockRecorder {
	return m.recorder
}

// Charge mocks base method.
func (m *MockPaymentPort) Charge(ctx context.Context, order *domain.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Charge", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// Charge indicates an expected call of Charge.
func (mr *MockPaymentPortMockRecorder) Charge(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Charge", reflect.TypeOf((*MockPaymentPort)(nil).Charge), ctx, order)
}
